apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storageversionmigrations.migration.k8s.io
spec:
  group: migration.k8s.io
  names:
    kind: StorageVersionMigration
    listKind: StorageVersionMigrationList
    plural: storageversionmigrations
    singular: storageversionmigration
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
