apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagestates.migration.k8s.io
spec:
  group: migration.k8s.io
  names:
    kind: StorageState
    listKind: StorageStateList
    plural: storagestates
    singular: storagestate
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
